[package]
name = "okay_lib"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "cfg Lottery demonstration"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_with_cfgs = { path = "../lib_with_cfgs", version = "0.1" }